baseURL = "" 
languageCode = "ja" 
title = "My New Hugo Site" 
theme = "learn"
publishDir = "../docs" 
relativeURLs = true

[params]
#themeVariant = "red"
#themeVariant = "blue"
#themeVariant = "green"